### ISSUE TITLE
Artifacts when counting down from 10 to 9

### ISSUE THREAD

**Issue by livibetter** [StijnCaerts/countdown-c#2]
"10 to 9" is the case I saw, I believe there is also others.

One or two characters, from rendered big text "10" on either sides, were not probably cleared up.

**Comment by StijnCaerts** [comment]
can you describe more precise what you saw, or demonstrate with a screenshot?

**Comment by StijnCaerts** [comment]
I checked and saw the bug, it is fixed now by clearing the window before writing. Thanks for noticing!
